---
# tasks file for myrostadler.centos7_symfony4_website
- name: Get install directory
  set_fact: website_install_dir="/var/www/{{ website_install_dir_name }}"

- include: get-db-server-version.yml

- name: Show DB server version
  debug:
    msg: "{{ website_install_env_database_server_version }}"

- name: Add / replace default SSL config
  template:
    src: ssl.conf.j2
    dest: "{{ website_install_default_ssl_conf_file }}"
    force: true

- name: Add virtual host
  template:
    src: vhost.conf.j2
    dest: "{{ website_install_conf_scan_folder }}/{{ website_install_dir_name }}.conf"

- name: Zap old git checkout in /tmp
  file:
    path: "/tmp/{{ website_install_dir_name }}"
    state: absent

- name: Check out site git repo to /tmp, using SSH
  git:
    repo: "{{ website_install_repo_ssh_uri }}"
    version: "{{ website_install_repo_version }}"
    dest: "/tmp/{{ website_install_dir_name }}"
    clone: true
    accept_hostkey: true
  become: false

- name: Zap old installed website
  file:
    path: "{{ website_install_dir }}"
    state: absent

- name: "Copy repo checkout to {{ website_install_dir }}"
  command: "mv /tmp/{{ website_install_dir_name }} /var/www/"
  changed_when: false

- name: Add standard .env file
  template:
    src: env.j2
    dest: "{{ website_install_dir }}/.env"

- name: Add extra lines to .env file
  lineinfile:
    dest: "{{ website_install_dir }}/.env"
    line: "{{ item.name }}={{ item.value }}"
  with_items: "{{ website_install_env_extra }}"
  no_log: true

- name: Add useless but required .env.local.php file
  template:
    src: env.local.php.j2
    dest: "{{ website_install_dir }}/.env.local.php"

- name: Install php project libraries using composer
  composer:
    command: install
    working_dir: "{{ website_install_dir }}"
    # composer does not see scripts as secure when running as root, you would get a warning
    no_scripts: true
    # change this on prod
    no_dev: "{{ website_install_env_app_env != 'dev' }}"

#- name: Clean project cache using console
#  command: php bin/console cache:pool:clear cache.global_clearer
#  args:
#    chdir: "{{ website_install_dir }}"
#  changed_when: false

- name: Install project assets using console
  command: php bin/console assets:install
  args:
    chdir: "{{ website_install_dir }}"
  changed_when: false

- name: Run DB migrations using console
  command: php bin/console doctrine:migrations:migrate -n
  args:
    chdir: "{{ website_install_dir }}"
  changed_when: false

- name: Zap project cache folder
  file:
    path: "{{ website_install_dir }}/var/cache"
    state: absent

- name: "Ensure apache is the owner of and permissions are correct for {{ website_install_dir }}"
  file:
    dest: "{{ website_install_dir }}"
    owner: apache
    group: apache
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Ensure public folder permissions are relaxed
  file:
    path: "{{ item }}"
    mode: '775'
    recurse: true
    state: directory
    owner: apache
  with_items:
    - "{{ website_install_dir }}/public"
  when: website_install_type is defined and website_install_type == 'symfony4'

- name: Ensure var folder permissions are relaxed
  file:
    path: "{{ item }}"
    mode: '777'
    recurse: true
    state: directory
    owner: apache
  with_items:
    - "{{ website_install_dir }}/var"
  when: website_install_type is defined and website_install_type == 'symfony4'

- name: Restart Apache
  service:
    name: httpd
    state: restarted